
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author senrith
 */
public class form extends javax.swing.JFrame {
        
        String dataCon="net.ucanaccess.jdbc.UcanaccessDriver";
        
        Connection sqlCon=null;
        PreparedStatement pst=null;
        ResultSet rs=null;
    /**
     * Creates new form form
     */
    public form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUName = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtContact = new javax.swing.JTextField();
        txtSex = new javax.swing.JTextField();
        txtNIC = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtRePassword = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtUName, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 80, 220, -1));
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 111, 220, -1));
        getContentPane().add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 142, 220, -1));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 173, 220, -1));
        getContentPane().add(txtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 204, 220, -1));
        getContentPane().add(txtSex, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 235, 220, -1));
        getContentPane().add(txtNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 269, 220, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("U S E R  N A M E");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 82, 128, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("N A M E");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 113, 128, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("A D D R E S S");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 144, 128, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("E  M A I L ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 175, 128, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("C O N T A C T ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 206, 128, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("S E X ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 237, 128, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("N I C ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 271, 128, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("P A S S W O R D");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 308, 128, -1));
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 306, 220, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("R E  P A S S W O R D");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 346, 160, -1));
        getContentPane().add(txtRePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 344, 220, -1));

        jButton1.setBackground(new java.awt.Color(0, 102, 51));
        jButton1.setText("R E J I S T E R");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 289, -1));

        jButton2.setBackground(new java.awt.Color(0, 102, 51));
        jButton2.setText("L O G I N");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 289, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 51));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/down-arrow.png"))); // NOI18N
        jLabel10.setText("     A l R E A D Y  H A V E  A C C O U N T");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 277, 27));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Supermarkettips.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        new login().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            try {
                Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
                sqlCon=DriverManager.getConnection("jdbc:ucanaccess://J:\\Net Been\\GroserySystem\\rejister.accdb");
                
                 String stNo1=txtUName.getText();
                   String stNo=null;
                       
                   String query1="SELECT username FROM reginformation WHERE  username=? ";
                    stNo="";
                   pst=sqlCon.prepareStatement(query1);
                   pst.setString(1,stNo1);
                   rs=pst.executeQuery();
                   
                   
                   while (rs.next()){
                        stNo=rs.getString("username");
                   }
                    
                    
                       
                       
                   if(stNo.equals(stNo1)){
                       JOptionPane.showMessageDialog(this,"Re-Check St No");

                             
                   }else{
                   String password1=txtPassword.getText();
             String password2=txtRePassword.getText();
             String uname=txtUName.getText();
            
             if(!uname.equals("")){
                 if((!password1.equals(""))&&(!password2.equals(""))){
                    if(password1.equals(password2)){
                    
                        String query="INSERT INTO reginformation(username,name,address,email,contact,sex,nic,password)VALUES(?,?,?,?,?,?,?,?)"; 
                        
                        pst=sqlCon.prepareStatement(query);
            
                        String username=txtUName.getText();
                        String name=txtName.getText();
                        String address=txtAddress.getText();
                        String email=txtEmail.getText();
                        String contact=txtContact.getText();
                        String sex=txtSex.getText();
                        String nic=txtNIC.getText();
                        String password=txtPassword.getText();
                 
                        pst.setString(1, username);
                        pst.setString(2, name);
                        pst.setString(3, address);
                        pst.setString(4, email);
                        pst.setString(5, contact);
                        pst.setString(6, sex);
                        pst.setString(7, nic);
                        pst.setString(8, password);
            
                        pst.executeUpdate();
            
                        JOptionPane.showMessageDialog(this,"Rejister Successful");
            
                        txtUName.setText("");
                        txtName.setText("");
                        txtSex.setText("");
                        txtEmail.setText("");
                        txtContact.setText("");
                        txtUName.setText("");
                        txtPassword.setText("");
                        txtAddress.setText("");
                
                        this.setVisible(false);
                        new login().setVisible(true);
                        }
                        else{
                        JOptionPane.showMessageDialog(this,"User Name Existed ");
                        txtPassword.setText("");
                        txtRePassword.setText("");
                 
                    }
                 }
             }
                   
                   
                   }
                
                
                
                
                
             
             
           
                
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(form.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(form.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNIC;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtRePassword;
    private javax.swing.JTextField txtSex;
    private javax.swing.JTextField txtUName;
    // End of variables declaration//GEN-END:variables
}
